name: Sync Hugging Face Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Git LFS
      run: |
        sudo apt-get install git-lfs
        git lfs install

    - name: Clone Hugging Face Model Repository
      env:
        HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
      run: |
        git clone https://huggingface.co/mogoi/kogpt2_refund
        cd MODEL_NAME
        git lfs pull

    - name: Push to GitHub
      run: |
        cd MODEL_NAME
        git remote add github https://github.com/ringringring-capstone/ringringring_ai.git
        git push github main
